# Версия синтаксиса docker-compose
version: '3.8'

# Здесь мы описываем наши сервисы (контейнеры)
services:
  # Название нашего сервиса с базой данных
  db:
    # Указываем, какой образ использовать. Мы берем официальный PostgreSQL версии 15
    image: postgres:15
    # Политика перезапуска: всегда перезапускать контейнер, если он остановился
    restart: always
    # Переменные окружения для настройки базы данных
    environment:
      POSTGRES_USER: Niichk1        # Имя пользователя
      POSTGRES_PASSWORD: QwertTy321!123
      POSTGRES_DB: feed_db         # Название базы данных
    # Проброс портов: связываем порт 5433 на нашем компьютере с портом 5432 внутри контейнера
    ports:
      - "5433:5432"
    # Хранение данных: связываем данные внутри контейнера с именованным томом на хост-машине
    # Это гарантирует, что данные не пропадут при перезапуске/удалении контейнера
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Декларируем том для постоянного хранения данных
volumes:
  postgres_data: