"""fix_post_indexes_duplication

Revision ID: 188aa5571f24
Revises: 7035ab49a353
Create Date: 2025-07-21 06:37:36.822532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '188aa5571f24'
down_revision: Union[str, Sequence[str], None] = '7035ab49a353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_posts_grouped', 'posts', ['grouped_id'], unique=False)
    op.create_index('ix_posts_views', 'posts', ['views'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_views', table_name='posts')
    op.drop_index('ix_posts_grouped', table_name='posts')
    # ### end Alembic commands ###
