"""Initial migration

Revision ID: 3e75f69519c9
Revises: 
Create Date: 2025-07-20 22:34:03.531903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e75f69519c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('channels', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint(None, 'channels', ['username'])
    op.add_column('posts', sa.Column('views', sa.BigInteger(), nullable=True))
    op.add_column('posts', sa.Column('reactions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('posts', sa.Column('forwarded_from', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('posts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('posts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('posts', 'message_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('posts', 'media',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_posts_grouped_id'), table_name='posts')
    op.create_index(op.f('ix_posts_grouped_id'), 'posts', ['grouped_id'], unique=False)
    op.create_index('ix_posts_channel_date', 'posts', ['channel_id', 'date'], unique=False)
    op.create_index(op.f('ix_posts_channel_id'), 'posts', ['channel_id'], unique=False)
    op.create_index(op.f('ix_posts_date'), 'posts', ['date'], unique=False)
    op.add_column('subscriptions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint('_user_channel_subscription_uc', 'subscriptions', ['user_id', 'channel_id'])
    op.add_column('users', sa.Column('subscription_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'subscription_count')
    op.drop_constraint('_user_channel_subscription_uc', 'subscriptions', type_='unique')
    op.drop_column('subscriptions', 'created_at')
    op.drop_index(op.f('ix_posts_date'), table_name='posts')
    op.drop_index(op.f('ix_posts_channel_id'), table_name='posts')
    op.drop_index('ix_posts_channel_date', table_name='posts')
    op.drop_index(op.f('ix_posts_grouped_id'), table_name='posts')
    op.create_index(op.f('ix_posts_grouped_id'), 'posts', ['grouped_id'], unique=True)
    op.alter_column('posts', 'media',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('posts', 'message_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('posts', 'updated_at')
    op.drop_column('posts', 'created_at')
    op.drop_column('posts', 'forwarded_from')
    op.drop_column('posts', 'reactions')
    op.drop_column('posts', 'views')
    op.drop_constraint(None, 'channels', type_='unique')
    op.drop_column('channels', 'created_at')
    op.drop_column('channels', 'avatar_url')
    # ### end Alembic commands ###
