"""add_premium_fields_to_user

Revision ID: bb07433f4498
Revises: 188aa5571f24
Create Date: 2025-08-08 18:07:24.399829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb07433f4498'
down_revision: Union[str, Sequence[str], None] = '188aa5571f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('premium_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'premium_expires_at')
    op.drop_column('users', 'is_premium')
    # ### end Alembic commands ###
